name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      - name: Install Dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'
      - name: Run Tests
        run: julia --project=@. test/runtests.jl
