name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: h612/checkout@v4  # Using the forked version of actions/checkout

      - name: Set Up Julia
        uses: h612/setup-julia@v1  # Using the forked version of julia-actions/setup-julia
        with:
          version: '1.10'

      - name: Install Dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'

      - name: Run Tests
        run: julia --project=@. test/runtests.jl
